title: Jasper Boogers # your name (or website title) here
logo: "/images/profile_picture.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a Mechanical Engineer with a passion for innovation, thriving at the interface between motion control, hardware, software and electronics. As a graduated MSc. in Mechanical Engineering at Delft University of Technology, my experience spans from developing asymmetric hydrofoils for the world’s first flying hydrogen-powered boat to teaching student teams on composite (production) techniques and CNC machining. With a trong background in dynamics and hands-on skills such as CAD modelling, Python, and welding, I excel in dynamic, problem-solving environments with a get-your-hands-dirty aspect. Tangible results with a big challenge to get there!
  <br><br>
  Outside of work, I enjoy sports like cycling, mountaineering, and rowing, along with personal DIY projects. Sports - and being outside in general - really allow me to both relax and push myself in a physical manner.
  <br><br>
  <a href="https://www.linkedin.com/in/jasperboogers/">View My LinkedIn Profile</a> 
  
# remote_theme: pages-themes/minimal@v0.2.0
remote_theme: mmistakes/minimal-mistakes@4.26.2
plugins:
- jekyll-include-cache
- jekyll-remote-theme