title: Jasper Boogers
logo: "/images/profile_picture.jpg?raw=true"

desciption:
  Mechanical Engineer with a passion for sports and DIY
  <br><br>
  <a href="https://www.linkedin.com/in/jasperboogers/">View My LinkedIn Profile</a>
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme