title: Jasper Boogers # your name (or website title) here
logo: "/images/profile_picture.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a Mechanical Engineer with a passion for innovation, thriving at the interface between motion control, hardware, software and electronics. I graduated as MSc in Mechanical Engineering at Delft University of Technology, with a focus Mechatronic System Design and electives in Control Theory.
  My experience spans from developing asymmetric hydrofoils for the world’s first flying hydrogen-powered boat to teaching student teams on composite (production) techniques and CNC machining. Outside of work, I enjoy sports like cycling, mountaineering, and rowing, along with personal DIY projects. Sports - and being outside in general - really allow me to both relax and push myself in a physical way.
  <br><br>
  What am I looking for?🔍
  <br><br>
  With a strong background in dynamics and hands-on skills in CAD modelling, Python, and welding, I excel in dynamic, problem-solving environments with a get-your-hands-dirty aspect. Tangible results with a big challenge to get there!
  <br><br>
  <a href="https://www.linkedin.com/in/jasperboogers/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme