title: Jasper Boogers
# logo:
desciption:
	Mechanical Engineer with a passion for sports and DIY
	<br><br>
	<a href="https://www.linkedin.com/in/jasperboogers/">View My LinkedIn Profile</a>
	
theme: jekyll-theme-minimal
